spring:
  profiles.active: dev
---
spring:
  profiles: dev
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update 
    hibernate.show_sql: true
    #entitymanager.packagesToScan: /
  datasource:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://159.203.220.71:3306/world
    username: root
    password: admin
  jmx:
    enabled: false

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest
  version: 0.3.0
  description: spring boot docker app
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

hotel.service:
  name: 'default profile:'
---
spring:
  profiles: test
  jmx:
    enabled: false  
  datasource:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://159.203.220.71:3306/world
    username: root
    password: admin  
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: create-drop 
    hibernate.show_sql: true
  
security:
  basic:
    enabled: false    

hotel.service:
  name: 'test profile:'
