spring:
  profiles.active: dev
---
spring:
  profiles: dev

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://159.203.220.71:3306/world
    username: root
    password: admin

server:
  port: 8090
  
spring.jpa:
    hibernate.ddl-auto: update  

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest
  version: 0.3.0
  description: spring boot docker app
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

hotel.service:
  name: 'default profile:'
---
spring:
  profiles: test

spring.jmx:
   enabled: false  

spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://159.203.220.71:3306/world
    username: root
    password: admin  
  
spring.jpa:
    hibernate.ddl-auto: create-drop
    
security:
  basic:
    enabled: false    

hotel.service:
  name: 'test profile:'
